@echo off
echo Launching emulator...
start /B flutter emulators --launch Medium_Phone_API_36.1
echo Waiting for emulator to start (30 seconds)...
timeout /t 30 /nobreak
echo Running Flutter app...
flutter run
